<div class="container margem-acima">
    <div class="secundario">
      <h1>Direito Autoral</h1>
        <p>É o direito que protege trabalhos publicados e não publicados nas áreas da literatura, teatro, música e coreografias de dança, filmes, fotografias, pinturas, esculturas e outros trabalhos visuais de arte como programas de computador (softwares). O direito autoral protege a expressão de idéias e reserva para seus autores o direito exclusivo de reproduzir seus trabalhos.</p>
        <p>A lei que versa sobre direitos do autor no caso da proteção de obras literárias e artísticas é a nº. 9610, de 19 de fevereiro de 1998. A instituição responsável pelo registro é a Biblioteca Nacional, definida na Lei n. 5988, de 14 de dezembro de 1973. Outras instituições nos estados podem, mediante convênio com a Biblioteca Nacional, se credenciar como escritórios de representação.</p>
        <p>É importante esclarecer que de forma diferente do que acontece com a patente ou outros instrumentos de propriedade industrial, a proteção aos direitos que trata a lei independe de registro, sendo facultado ao autor registrar a sua obra em órgão descrito por lei (art. 18 e 19).</p>

        <h2>SÃO OBRAS INTELECTUAIS PROTEGIDAS (ART. 7º):</h2>
        <ul>
            <li>textos de obras literárias, artísticas ou científicas;</li>
            <li>obras coreográficas e pantomímicas, cuja execução cênica se fixa por escrito ou por outra qualquer forma;</li>
            <li>composições musicais tenham ou não letra;</li>
            <li>obras audiovisuais, sonorizadas ou não, inclusive as cinematográficas;</li>
            <li>obras fotográficas e as produzidas por qualquer processo análogo ao da fotografia;</li>
            <li>obras de desenho, pintura, gravura, escultura, litografia e arte cinética;</li>
            <li>projetos, esboços e obras plásticas concernentes à geografia, engenharia, topografia, arquitetura, paisagismo, cenografia e ciência;</li>
            <li>adaptações, traduções e outras transformações de obras originais, apresentadas como criação intelectual nova;</li>
            <li>os programas de computador (os programas de computador são objeto de legislação específica, observadas as disposições desta lei que lhes sejam aplicáveis);</li>
            <li>as coletâneas ou compilações, antologias, enciclopédias, dicionários, bases de dados e outras obras, que, por sua seleção, organização ou disposição de seu conteúdo, constituam uma criação intelectual.</li>
        </ul>

        <h2>NÃO SÃO OBJETO DE PROTEÇÃO SEGUNDO A LEI DE DIREITOS AUTORAIS (ART. 8):</h2>
        <ul>
            <li>idéias, procedimentos normativos, sistemas, métodos, projetos ou conceitos matemáticos como tais;</li>
            <li>esquemas, planos ou regras para realizar atos mentais, jogos ou negócios;</li>
            <li>formulários em branco para serem preenchidos por qualquer tipo de informação científica ou não, e suas instruções;</li>
            <li>textos de tratados ou convenções, leis, decretos, regulamentos, decisões judiciais e demais atos oficiais;</li>
            <li>informações de uso comum tais como calendários, agendas, cadastro ou legendas;</li>
            <li>nomes e títulos isolados;</li>
            <li>aproveitamento industrial ou comercial das idéias contidas nas obras.</li>
        </ul>

        <h2>DA VALIDADE DAS PROTEÇÕES E DO DOMÍNIO PÚBLICO</h2>
        <ul>
            <li>Validade da proteção autoral: inicia-se a partir da criação da obra e perdura por 70 anos contados de 1º de janeiro do ano subseqüente ao falecimento do autor (art. 42). No caso de co-autoria, esse período é de 70 anos seguinte à morte do último co-autor sobrevivente;</li>
            <li>Validade para obras anônimas ou pseudônimas: 70 anos contados de 1º de janeiro do ano imediatamente posterior ao da primeira publicação (art. 43);</li>
            <li>Validade para obras audiovisuais e fotográficas: 70 anos, a contar de 1º de janeiro do ano subseqüente ao de sua divulgação (art. 44);</li>
            <li>Domínio Público: além das obras em relação às quais decorreu o prazo de proteção aos direitos patrimoniais, pertencem ao domínio público às obras de autores falecidos que não tenham deixado sucessores e as de autor desconhecido, ressalvada a proteção legal aos conhecimentos étnicos e tradicionais (art. 45).</li>
        </ul>
    </div>
</div>