<div class="parallax">
      <div class="parallax-text">
        <h3 class="text-white">Registre sua marca</h3>
        <a class="btn btn-danger" href="#formulario">Registrar</a>
      </div>
      
    </div>

    <div class="container containertop mb-0">
      
      <div id="apresentacao" class="row">
        <div class="col-md-6">
          <img src="../img/brand.jpg" alt="" width="100%" id="img-apresentacao" class="wow fadeIn d-none d-md-block">
        </div>
        <div class="col-md-6">
          <div id="texto-apresentacao" class="wow fadeIn">
            <h3 class="text-center mb-4">Por que ter uma marca ou patente?</h3>
            <p>Registrar marcas, patentes e desenhos industriais é um procedimento fundamental para o empreendedor. Nenhum negócio está a salvo da pirataria: o que não faltam no mercado são exemplos de contravenções que ferem a propriedade intelectual. Além disso, ter uma marca registrada ou um produto patenteado no Instituto Nacional da Propriedade Industrial (Inpi) pode fazer toda a diferença na hora de negociar com investidores e parceiros. Muitos empreendedores preferem concentrar seus recursos em vendas e fluxo de caixa, porque acreditam que o registro só interessa para grandes corporações. Mas essa visão pode limitar o crescimento do negócio.</p>
            <a href="#formulario" class="btn btn-danger">Faça já sua cotação</a>
          </div>
        </div>
        
      </div>
      <hr class="barra mt-3"/>
    </div>

      <div id="servicos">
          <div class="row w-100 m-0">
            <div class="col-md items bg-white pb-3 titulo">
              <h3 class="mb-4">Serviços</h3>
            </div>
          </div>
        <div class="container mt-5">
          <div class="row">
            
            <div class="col-md items pb-3 direita">
              <i class="fas fa-search icon"></i>
              <h2>Consulta de marcas</h2>
              <p>Consulte conosco a disponibilidade de uma marca para seu negócio.</p>
              <a id="marca" href="#formulario" class="btn btn-danger btn-sm">Saiba mais</a>
            </div>
            <div class="col-md items pb-3">
              <i class="far fa-registered icon"></i>
              <h2>Registro de marcas</h2>
              <p>Protega sua marca conosco.</p>
              <a href="/registro_marcas" class="btn btn-danger btn-sm">Saiba mais</a>
            </div>
          </div>
          <div class="row">
            <div class="col-md items pb-3 pt-3 direita">
                <i class="far fa-copyright icon"></i>
                <h2>Registro de patentes</h2>
                <p>Registre sua patente conosoco, proteja suas criações.</p>
                <a href="/registro_patentes" class="btn btn-danger btn-sm">Saiba mais</a>

            </div>
            <div class="col-md items pb-3 pt-3">
                <i class="far fa-lightbulb icon"></i>
                <h2>Direito autoral</h2>
                <p>Registro de obra literária, músicas, partituras, ilustrações, logotipos, peças publicitárias dentre outros.</p>
                <a href="/direito_autoral" class="btn btn-danger btn-sm">Saiba mais</a>

            </div>
          </div>
          <div class="row">
            <div class="col-md items mb-5">
                <i class="fas fa-gavel icon"></i>
                <h2>Serviços jurídicos</h2>
                <p>Podemos proteger você em alguns processos juridicos.</p>
                <a href="/juridicos" class="btn btn-danger btn-sm">Saiba mais</a>

            </div>
          </div>
        

           <hr class="barra mt-3"/>
        </div>
      </div>

      <div class="container">

        <div id="empresa" class="my-5 wow fadeInLeft" data-wow-duration="0.5s">
          <div class="row somos">
            <div class="col-md-6" style="text-align: center;">
                <h2>Quem nós somos?</h2>
                <p>A Assemap é uma empresa que se consolidou ao longo dos anos, trabalhando com um conceito diferenciado no mercado de Propriedade Industrial, prestando assessoria especializada em encaminhamento e acompanhamento de registro de Marcas, Patentes e Direito Autoral, trabalhando com preço justo, agilidade na entrega de protocolos e qualidade nos serviços prestados.</p>
                <h2>Nossos valores</h2>
                <p>Possui uma equipe de profissionais experientes, sempre disponíveis para atendê-lo.</p>
            </div>

            <div class="col-md-6 central">
              <div class="assemap_img">
                <img src="../img/assemap.png" alt="" class="assemap-img">
              </div>
            </div>
          
            
          </div>
        </div>

        <hr class="barra"/>

        <div id="formulario" class="wow fadeInRight" data-wow-duration="0.5s">
          <form id="dados">
            <fieldset>
              <legend>Para mais informações, envie sua mensagem!</legend>
              <div class="form-group">
                <label for="formGroupExampleInput">E-mail</label>
                <input name="email" required="required" type="email" class="form-control" id="formGroupExampleInput" placeholder="Digite seu e-mail">
              </div>
              <div class="form-group">
                <label for="formGroupExampleInput2">Assunto</label>
                <input required="required" name="assunto" type="text" class="form-control" id="formGroupExampleInput2" placeholder="Digite o assunto">
              </div>
              <div class="form-group">
                <label for="formGroupExampleInput2">Mensagem</label>
                <textarea required="required" name="mensagem" type="text" class="form-control" id="formGroupExampleInput2" placeholder="Digite sua mensagem"></textarea> 
              </div>
              <div class="form-group">
                  <button type="submit" id="enviar" class="btn btn-danger">Enviar</button>
              </div>
            </fieldset>
          </form>

        </div>

        <div id="contato" >
          <div class="row">
            <div class="col-md-6">
            <h3>Fale Conosco</h3>
            <h4 class="fale">G.A. ASSEMAP ASSESSORIA EMPRESARIAL LTDA</h4>
            <a href="tel:5131810360" class="fale">Telefone: (51) 3181-0360</a>
            <h4 class="fale">Porto Alegre - RS</h4>
            <a href="mailto:assemap@assemap.com.br" title="" color="black" class="fale">Email: assemap@assemap.com.br</a>
            </div>
            <div class="col-md-6 mt-3 central">
              <a class="" href="https://api.whatsapp.com/send?phone=5551982281570">
                <img src="../img/whatsapp.png" alt="Mensagem Whatsapp" class="btn-whats"> 
              </a>
            </div>
          </div>
        </div>

      </div>