<div class="container margem-acima height-certo">
    <div class="secundario">
        <h1>Serviços Jurídicos</h1>
        <h2>Judicial:</h2>
        <div class="lista">
            <ul>
                <li>Ação ordinária</li>
                <li>Medida cautelar de busca e apreensão</li>
                <li>Contestação</li>
                <li>Recurso e orientação no âmbito geral.</li>
            </ul>
            <h2>Extrajudicial:</h2>
            <ul>
                <li>Notificação</li>
                <li>Elaboração de contratos de sigilo, licença de uso de marca e de direito autoral, exploração de patente e transferência de tecnologia</li>
                <li>Serviços administrativos junto ao INPI - oposição, contestação à oposição, cumprimento de exigência, recurso contra indeferimento, processo administrativo de nulidade, contestação ao processo administrativo de nulidade; pedido de caducidade, entre outros</li>
            </ul>
            <br />
            <br />
        </div>
    </div>
</div>
