<div class="container margem-acima">
    <div class="secundario">
        <h1>Registro de Marcas</h1>
        <p>Marca, segundo a lei brasileira, é todo sinal distintivo, visualmente perceptível, que identifica e distingue produtos e serviços, bem como certifica a conformidade dos mesmos com determinadas normas ou especificações técnicas. A marca registrada garante ao seu proprietário o direito de uso exclusivo no território nacional em seu ramo de atividade econômica. Ao mesmo tempo, sua percepção pelo consumidor pode resultar em agregação de valor aos produtos ou serviços.</p>
        <h2>Antes do pedido de marca</h2>
        <p>Antes de solicitar o pedido de marca, é importante definir a natureza do uso da marca e a sua forma de apresentação:</p>
        <div class="tab">
            <table class="table-margin" border="1">
                    <th>Naturezas da Marca </th>
                    <th>A que ela se aplica</th>
                <tr>
                    <td>Marca de Produto</td>
                    <td>Distinguir produtos de outros idênticos, semelhantes ou afins</td>
                </tr>
                <tr>
                    <td>Marca de Serviço</td>
                    <td>Distinguir serviços de outros idênticos, semelhantes ou afins</td>
                </tr>
                <tr>
                    <td>Marca Coletiva</td>
                    <td>Identificar produtos ou serviços provenientes de membros de um determinado grupo ou entidade</td>
                </tr>
                <tr>
                    <td>Marca de Certificação</td>
                    <td>Atestar a conformidade de produtos ou serviços a determinadas normas ou especificações técnicas </td>
                </tr>
            </table>
        </div>
        <table class="table-margin" border="1">
                <th>Formas de apresentação da marca </th>
                <th>A que se aplica</th>
            <tr>
                <td>Nominativa</td>
                <td>Sinal constituído apenas por palavras, ou combinação de letras e/ou algarismos, sem apresentação fantasiosa </td>
            </tr>
            <tr>
                <td>Mista</td>
                <td>Sinal que combina elementos nominativos e figurativos</td>
            </tr>
            <tr>
                <td>Figurativa</td>
                <td>Sinal constituído por desenho, imagem, formas fantasiosas em geral</td>
            </tr>
            <tr>
                <td>Tridimensional</td>
                <td>Sinal constituído pela forma plástica distintiva e necessariamente incomum do produto</td>
            </tr>
        </table>
        <h2>REGISTRO DE MARCA PASSO A PASSO:</h2>
        <h3>1º PASSO: BUSCA DE ANTERIORIDADE</h3>
        <p>A busca de anterioridade visa verificar se a marca apresenta alguma anterioridade no INPI, ou seja, verifica-se se há no órgão registro de marca idêntica ou semelhante a que se deseja registrar. Essa pesquisa tona o encaminhamento de registro mais seguro e mais provável.</p>
        <h3>2º PASSO: DEPÓSITO </h3>
        <p>Caso o resultado da busca não apresente nenhuma colidência ou anterioridade, é feito o depósito da marca, gerando um número de processo que identificará a marca junto ao INPI.<br>
        <br> São necessários para encaminhamento da marca:<br>
        <br> - Cartão CNPJ ou comprovação da atividade exercida através do órgão regulamentador ( Exemplos: carteira de músico, OAB, CREA).<br>
        <br> -  Cópia simples do contrato social.<br>
        <br> -  Logotipo (se a marca for mista ou figurativa).<br>
        <br> - Procuração </p>
        <h3>3º PASSO: PUBLICAÇÃO DO REGISTRO</h3>
        <p>Em torno de 60 dias após o encaminhamento, o pedido de registro é publicado.<br>
        <br> Após essa publicação abre-se o prazo de 60 dias para apresentação de oposição de terceiros que se sintam prejudicados, havendo oposição deve-se proceder com a manifestação.<br>
        <br> Não havendo oposição, o processo fica tramitando no INPI aguardando seu julgamento.</p>
        <h3>4º PASSO: DEFERIMENTO</h3>
        <p>Em média 2 anos após encaminhado o registro , O INPI julgará o processo.<br>
        <br> Sendo aprovado o registro, deverá ser recolhida a taxa decenal, que corresponde ao pagamento dos primeiros 10 anos de utilização da marca.<br>
        <br> Caso indeferido o registro, cabe ainda recurso contra tal decisão.</p>
        <h3>5º PASSO: CONCESSÃO DO REGISTRO</h3>
        <p>Aprovada a marca e devidamente recolhida a taxa decenal, será publicada a concessão da marca, no qual será contada a vigência e expedido certificado de registro de marca.</p>
        <h3>6º PASSO: PRORROGAÇÕES</h3>
        <p>O registro de marca deve ser renovado a cada dez anos, sendo de suma importância a sua constante utilização.</p>
    </div>
</div>