<div class="container margem-acima">
    <div class="secundario">
        <h1>Registro de Patentes</h1>
            <p>Patente é um título de propriedade temporária sobre uma invenção ou modelo de utilidade, outorgado pelo Estado aos inventores ou autores ou outras pessoas físicas ou jurídicas detentoras de direitos sobre a criação.</p>
            <h2>TIPOS DE PATENTE:</h2>
            <h3>PATENTE DE INVENÇÃO (PI)</h3>
            <p>Produtos ou processos que atendam aos requisitos de atividade inventiva, novidade e aplicação industrial.<br>
            <br>
                Sua validade é de 20 anos a partir da data do depósito</p>
            <h3>MODELO DE UTILIDADE (MU)</h3>
            <p>Objeto de uso prático, ou parte deste, suscetível de aplicação industrial, que apresente nova forma ou disposição, envolvendo ato inventivo, que resulte em melhoria funcional no seu uso ou em sua fabricação.<br>
                <br>
            Sua validade é de 15 anos a partir da data do depósito.</p>
            <h4>ATENÇÃO</h4>
            <p>Não se pode patentear um processo como Modelo de Utilidade, somente como Patente de Invenção.</p>
            <h3>CERTIFICADO DE ADIÇÃO DE INVENÇÃO (C)</h3>
            <p>Aperfeiçoamento ou desenvolvimento introduzido no objeto da invenção, mesmo que destituído de atividade inventiva, porém ainda dentro do mesmo conceito inventivo.<br>
            <br>
            O certificado será acessório à patente e com mesma data final de vigência desta. </p>
            <h3>QUAIS SÃO OS DOCUMENTOS NECESSÁRIOS?</h3>
            <p>- Relatório descritivo;<br>
            <br>   
            - CNPJ ou RG e CPF do requerente.<br>
            <br>
            - Procuração</p>
            <h2>REGISTRO DE PATENTE PASSO A PASSO:</h2>
            <h3>1º PASSO: ELABORAÇÃO DO RELATÓRIO DESCRITIVO</h3>
            <p>Para encaminhamento do registro de uma patente, deve ser elaborado um relatório descrevendo todas as particularidades do invento, bem como o que deseja-se proteger no mesmo.</p>
            <h3>2º PASSO:  DEPÓSITO DE PATENTE</h3>
            <p>Após elaboração do relatório descritivo, procede-se com o encaminhamento do registro da patente, onde será gerado um número de protocolo.</p>
            <h3>3º PASSO: PUBLICAÇÃO</h3>
            <p>A publicação da patente ocorre após 18 meses contados da data de depósito ou da prioridade, para pedidos do exterior</p>
            <h3>4º PASSO: PADIDO DE EXAME</h3>
            <p>O Pedido de exame deverá ser solicitado pelo interessado em até 36 meses da data de depósito, sendo que o julgamento da patente ocorre cerca de 6 anos contados da data de depósito.<br>
            <br>
            Em determinados casos, o interessado pode solicitar o exame prioritário de patente.</p>
            <h3>ANUIDADES</h3>
            <p class="table-margin">É cobrado pelo INPI anuidade desde o pedido de registro de patente até o final de sua vigência. As anuidades são devidas a partir do 24º mês de depósito.</p>
    </div>
</div>